package modelo;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos
//  @ File Name : AsignacionEmpleadoPlanificacion.java
//  @ Date : 14/01/2012
//  @ Author : Emma
//
//

public class AsignacionEmpleadoPlanificacion {
    private int id;
    
    private DetalleSubObraXTarea asignacionTareaCotizacion;
    private List<Empleado> empleados;

    public AsignacionEmpleadoPlanificacion() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public DetalleSubObraXTarea getAsignacionTareaCotizacion() {
        return asignacionTareaCotizacion;
    }

    public void setAsignacionTareaCotizacion(DetalleSubObraXTarea asignacionTareaCotizacion) {
        this.asignacionTareaCotizacion = asignacionTareaCotizacion;
    }

    

    public List<Empleado> getEmpleados() {
        return empleados;
    }

    public void setEmpleados(List<Empleado> empleados) {
        this.empleados = empleados;
    }
    
}
