//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : Empleado.java
//  @ Date : 14/06/2010
//  @ Author : 
//
//




public class Empleado {
	private Object fechaAlta;
	private Object fechaBaja;
	private Object legajo;
	private Object rango;
	private ientos.Capacitacion capacitacion;
	private ientos.ItemIndumentaria indumentaria;
	private ientos.Especialidad especialiades;
	public void crear() {
	
	}
	
	public void mostrarEmpleado() {
	
	}
	
	public void mostrarRangoEmpleado() {
	
	}
	
	public void mostrarEspecialidades() {
	
	}
	
	public void mostrarCapacitacion() {
	
	}
	
	public void crear() {
	
	}
	
	public void crearEspecialidades() {
	
	}
	
	public void crearDomicilio() {
	
	}
	
	public void crearTelefonos() {
	
	}
	
	public void esEmpleado() {
	
	}
	
	public void buscarLegajoEmpleado() {
	
	}
	
	public void mostrarApellidoYNombre() {
	
	}
	
	public void getEmpleado() {
	
	}
	
	public void esTuTipo() {
	
	}
	
	public void buscarNombresEmpleadosActivos() {
	
	}
	
	public void buscarEmpleadosActivosConFechaDeVencimiento() {
	
	}
	
	public void mostrarEmpleadosDeEseTipoYMaximaFechaDeVencimiento() {
	
	}
	
	public void mostrarEmpleadoActivo() {
	
	}
	
	public void estaAsignado() {
	
	}
	
	public void fechaVencimientoCapacitación() {
	
	}
}
