package modelo;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : Empleado.java
//  @ Date : 14/06/2010
//  @ Author : Iuga
//
//




public class Empleado extends Persona {

	//private Date fechaAlta;
	//private Date fechaBaja;
	private int legajo;
	private String rango;
	//private ArrayList capacitacion;
	//private ArrayList indumentaria;
	//private ArrayList<Especialidad> especialidades;
        
	private Set indumentaria;
	private Set<Especialidad> especialidades;
        private Set<Capacitacion> capacitaciones;
        private EstadoEmpleado estado;
        private Date fechaIngreso;




   
public Empleado(int leg,String nom,String apell,Date fechadeNac,Date fechaIng,TipoDocumento tipoDoc,String nroDoc,String cuil, String email,Domicilio domicilio , ArrayList<TipoEspecialidad> tipoEspecialiades,ArrayList<RangoEspecialidad> rangoEspecialiades , ArrayList<String> listaNroTel, ArrayList<TipoTelefono> listaTipoTel,ArrayList<TipoCapacitacion> listaTipoCapacitaciones, ArrayList<Date> listaVencimientoCapacitaciones, Date fecha_Alta)
    {
        legajo=leg;
        super.setNombre(nom);
        super.setApellido(apell);
        super.setFechadeNac(fechadeNac);
        super.setTipoDoc(tipoDoc);
        super.setNroDoc(nroDoc);
        super.setCuil(cuil);
        super.setEmail(email);
        super.setDomicilio(domicilio);
        setEspecialidades(tipoEspecialiades, rangoEspecialiades);
        //especialiades= new ArrayList();
        //indumentaria= new ArrayList();
        //capacitacion= new ArrayList();
        super.setFechaAlta(fecha_Alta);
        super.setTelefonos(listaNroTel, listaTipoTel);
        setCapacitaciones(listaTipoCapacitaciones,listaVencimientoCapacitaciones);
        estado=new EstadoEmpleadoActivo();
        fechaIngreso =fechaIng;

    }
     public Empleado(int leg,String nom,String apell,Date fechadeNac,Date fechaIng,TipoDocumento tipoDoc,String nroDoc,String cuil, String email, String calleD, int numeroD, int pisoD, String deptoD, String codigoPostalD, Barrio barrioD , ArrayList<TipoEspecialidad> tipoEspecialiades,ArrayList<RangoEspecialidad> rangoEspecialiades , ArrayList<String> listaNroTel, ArrayList<TipoTelefono> listaTipoTel,ArrayList<TipoCapacitacion> listaTipoCapacitaciones, ArrayList<Date> listaVencimientoCapacitaciones, Date fecha_Alta)
    {
        legajo=leg;
        super.setNombre(nom);
        super.setApellido(apell);
        super.setFechadeNac(fechadeNac);
        super.setTipoDoc(tipoDoc);
        super.setNroDoc(nroDoc);
        super.setCuil(cuil);
        super.setEmail(email);
        //super.setDomicilio(domicilio);
        setEspecialidades(tipoEspecialiades, rangoEspecialiades);
        //especialiades= new ArrayList();
        //indumentaria= new ArrayList();
        //capacitacion= new ArrayList();
        super.setFechaAlta(fecha_Alta);
        super.setDomicilio(calleD,  numeroD,  pisoD,  deptoD, codigoPostalD,  barrioD);
        super.setTelefonos(listaNroTel,  listaTipoTel);
        setCapacitaciones(listaTipoCapacitaciones,listaVencimientoCapacitaciones);
        estado=new EstadoEmpleadoActivo();
        fechaIngreso =fechaIng;
    }
     public Empleado()
     {
        /* especialiades= new ArrayList();
         indumentaria= new ArrayList();
         capacitacion= new ArrayList();*/
    }

     public EstadoEmpleado getEstado()
     {
         return estado;
     }
     public void setEstado(EstadoEmpleado ee)
     {
         estado=ee;
     }
     public Date getFechaIngreso()
     {
         return fechaIngreso;
     }
     public void setFechaIngreso(Date fi)
     {
         fechaIngreso=fi;
     }
    public Set getCapacitaciones() {
        return capacitaciones;
    }

    public void setCapacitaciones(Set capacitacion) {
        this.capacitaciones = capacitacion;
    }

    public Set<Especialidad> getEspecialidades() {
        return especialidades;
    }

    public void setEspecialidades(Set<Especialidad> especialiades) {
        this.especialidades = especialiades;
    }
   /* public List getCapacitacion() {
        return capacitacion;
    }

    public void setCapacitacion(ArrayList capacitacion) {
        this.capacitacion = capacitacion;
    }

    public ArrayList<Especialidad> getEspecialidades() {
        return especialidades;
    }

    public void setEspecialidades(ArrayList<Especialidad> especialiades) {
        this.especialidades = especialiades;
    }*/
    public void setEspecialidades(ArrayList<TipoEspecialidad> tipoEspecialiades,ArrayList<RangoEspecialidad> rangoEspecialiades)
    {
        especialidades= new HashSet();
        for(int i=0; i< tipoEspecialiades.size();i++)
        {
           Especialidad especialidad = new Especialidad(tipoEspecialiades.get(i), rangoEspecialiades.get(i));
           especialidades.add(especialidad);
        }
    }

    public void setCapacitaciones(ArrayList<TipoCapacitacion> tipoCapacitaciones,ArrayList<Date> vencimientosCapacitaciones)
    {
        capacitaciones= new HashSet();
        for(int i=0; i< tipoCapacitaciones.size();i++)
        {
           Capacitacion cap = new Capacitacion(tipoCapacitaciones.get(i), vencimientosCapacitaciones.get(i));
           capacitaciones.add(cap);
        }
    }
    /*public void setEspecialidades(ArrayList<TipoEspecialidad> tipoEspecialiades,ArrayList<RangoEspecialidad> rangoEspecialiades)
    {
        especialidades= new ArrayList();
        for(int i=0; i< tipoEspecialiades.size();i++)
        {
           Especialidad especialidad = new Especialidad(tipoEspecialiades.get(i), rangoEspecialiades.get(i));
           especialidades.add(especialidad);
        }
    }*/
    

    
    public Set getIndumentaria() {
        return indumentaria;
    }

    public void setIndumentaria(Set indumentaria) {
        this.indumentaria = indumentaria;
    }
    /*
  public List getIndumentaria() {
        return indumentaria;
    }

    public void setIndumentaria(ArrayList indumentaria) {
        this.indumentaria = indumentaria;
    }
 */
    public int getLegajo() {
        return legajo;
    }

    public void setLegajo(int legajo) {
        this.legajo = legajo;
    }

    public String getRango() {
        return rango;
    }

    public void setRango(String rango) {
        this.rango = rango;
    }



        public void crear() {
	
	}
	
	public void mostrarEmpleado() {
	
	}
	
	public void mostrarRangoEmpleado() {
	
	}
	
	public void mostrarEspecialidades() {
	
	}
	
	public void mostrarCapacitacion() {
	
	}
	
	public void crearEspecialidades() {
	
	}
	
	public void crearDomicilio() {
	
	}
	
	public void crearTelefonos() {
	
	}
	
	public void esEmpleado() {
	
	}
	
	public void buscarLegajoEmpleado() {
	
	}
	
	public void mostrarApellidoYNombre() {
	
	}
	
	public void getEmpleado() {
	
	}
	
	public void esTuTipo() {
	
	}
	
	public void buscarNombresEmpleadosActivos() {
	
	}
	
	public void buscarEmpleadosActivosConFechaDeVencimiento() {
	
	}
	
	public void mostrarEmpleadosDeEseTipoYMaximaFechaDeVencimiento() {
	
	}
	
	public void mostrarEmpleadoActivo() {
	
	}
	
	public void estaAsignado() {
	
	}
	
	public void fechaVencimientoCapacitacion() {
	
	}
}
