package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : EmpresaCliente.java
//  @ Date : 14/06/2010
//  @ Author : 
//
//




public class EmpresaCliente extends Empresa{
    private Planta plantas;

    public EmpresaCliente() {
    }

    public Planta getPlantas() {
        return plantas;
    }

    public void setPlantas(Planta plantas) {
        this.plantas = plantas;
    }

    // Sería el constructor...
    public void crear() {

    }

    public void mostrarLocalidad() {

    }

    public void mostrarPlanta(String nombre) {

    }

    public void getDatosEmpresaCliente() {

    }

    public void getNombre() {

    }

    public void getEmpresa(Planta planta) {

    }

    public void mostrarDatosRestantes() {

    }

    public void getEmpresaCliente(String nombre) {

    }

    public void getRazonSocialPlantas() {

    }

    public void esEstadoAlta() {

    }

    public void mostrarDatos() {

    }

    public void getCUIT() {

    }
}
