package modelo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : PresupuestoBase.java
//  @ Date : 08/10/2010
//  @ Author : 
//
//

public class PresupuestoBase {
    private int id;
    private Date fechaEstimadaInicioObra;
    private Date fechaEstimadaFinObra;
    private String version;
    private List<Etapa> etapas;
    private float porcConsumibles;
    private float IVA;

    private double ganancia;
    private double consumibles;

    public void crear() {

    }

    public void mostrarPlanificacionObra() {

    }

    public void mostrarGrupoDeTrabajo() {

    }

    public void mostrarEtapas() {

    }

    public void CalcularMontoTotal() {

    }

    public PresupuestoBase() {
    }

    public float getIVA() {
        return IVA;
    }

    public void setIVA(float IVA) {
        this.IVA = IVA;
    }

    public List<Etapa> getEtapas() {
        return etapas;
    }

    public void setEtapas(List<Etapa> etapas) {
        this.etapas = etapas;
    }

    public Date getFechaEstimadaFinObra() {
        return fechaEstimadaFinObra;
    }

    public void setFechaEstimadaFinObra(Date fechaEstimadaFinObra) {
        this.fechaEstimadaFinObra = fechaEstimadaFinObra;
    }

    public Date getFechaEstimadaInicioObra() {
        return fechaEstimadaInicioObra;
    }

    public void setFechaEstimadaInicioObra(Date fechaEstimadaInicioObra) {
        this.fechaEstimadaInicioObra = fechaEstimadaInicioObra;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public float getPorcConsumibles() {
        return porcConsumibles;
    }

    public void setPorcConsumibles(float porcConsumibles) {
        this.porcConsumibles = porcConsumibles;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public void addEtapa(Etapa e)
    {
        if(this.etapas==null)
        {
            this.etapas = new ArrayList<Etapa>();
        }
        this.etapas.add(e);
    }

    public double getConsumibles() {
        return consumibles;
    }

    public void setConsumibles(double consumibles) {
        this.consumibles = consumibles;
    }

    public double getGanancia() {
        return ganancia;
    }

    public void setGanancia(double ganancia) {
        this.ganancia = ganancia;
    }

    
}
