package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : TransporteDeMaterialesYHerramientas.java
//  @ Date : 08/10/2010
//  @ Author : 
//
//

public class TransporteDeMaterialesYHerramientas extends Recurso {
    public String toString()
    {
        return "TransporteDeMaterialesYHerramientas";
    }
}
