/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pantallaSeleccionarProveedorPresupuesto.java
 *
 * Created on 10-sep-2010, 15:39:00
 */

package vista.planificacion_old;

import controlador.planificacion_old.GestorRegistrarAsignacionMateriales;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import util.LogUtil;
import util.NTupla;
import util.StringUtil;
import util.TablaUtil;

/**
 *
 * @author Administrador
 */
public class pantallaSeleccionarMaterialesEtapa extends javax.swing.JInternalFrame {
    private GestorRegistrarAsignacionMateriales gestorRAM;
    private int idEtapa;
    private int idTarea;
    private boolean banHayMaterialesProyecto;
    /** Creates new form pantallaSeleccionarProveedorPresupuesto */
    public pantallaSeleccionarMaterialesEtapa() {
        initComponents();
    }

    pantallaSeleccionarMaterialesEtapa(GestorRegistrarAsignacionMateriales gestorRAM,int idEtapa,int idTarea) {
        initComponents();
        this.gestorRAM = gestorRAM;
        this.idEtapa=idEtapa;
        this.idTarea = idTarea;
        this.banHayMaterialesProyecto=true;
        mostrarDetallesMaterialesOtrasTareas();
    }

    private void mostrarDetallesMaterialesOtrasTareas()
    {
        DefaultTableModel modelo = (DefaultTableModel)tbMaterialesOtrasTareas.getModel();

        // VACIO LA TABLA
        TablaUtil.vaciarDefaultTableModel(modelo);

        HashMap<Integer,NTupla> listaMOT = gestorRAM.mostrarDetallesMaterialesOtrasTareas(this.idEtapa,this.idTarea);

        Iterator itm = listaMOT.entrySet().iterator();

        if(listaMOT.size()>0){
            int cantidad = 0;
            double precio = 0;
            while (itm.hasNext())
            {
                NTupla ntp = (NTupla)((Map.Entry)itm.next()).getValue();
                Object[] fila = new Object[4];
                fila[0] = ntp;
                Object[] o = (Object[]) ntp.getData();
                fila[1] = o[0];
                fila[2] = o[1];
                cantidad = (Integer)o[1];
                precio = (Double)o[2];
                double subtotal = cantidad*precio;
                fila[3] = subtotal;

                modelo.addRow(fila);
            }
        }else{
            this.banHayMaterialesProyecto = false;
        }
    }

    public boolean isBanHayMaterialesProyecto() {
        return banHayMaterialesProyecto;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProveedor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMaterialesOtrasTareas = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Seleccione un Material de otras Tareas");

        panelProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el Material"));

        tbMaterialesOtrasTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nombre", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMaterialesOtrasTareas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbMaterialesOtrasTareas);
        tbMaterialesOtrasTareas.getColumnModel().getColumn(2).setMinWidth(70);
        tbMaterialesOtrasTareas.getColumnModel().getColumn(2).setPreferredWidth(70);
        tbMaterialesOtrasTareas.getColumnModel().getColumn(2).setMaxWidth(80);
        tbMaterialesOtrasTareas.getColumnModel().getColumn(3).setMinWidth(70);
        tbMaterialesOtrasTareas.getColumnModel().getColumn(3).setPreferredWidth(70);
        tbMaterialesOtrasTareas.getColumnModel().getColumn(3).setMaxWidth(80);

        javax.swing.GroupLayout panelProveedorLayout = new javax.swing.GroupLayout(panelProveedor);
        panelProveedor.setLayout(panelProveedorLayout);
        panelProveedorLayout.setHorizontalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelProveedorLayout.setVerticalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconos/var/16x16/add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(tbMaterialesOtrasTareas.getSelectedRow()>=0)
        {
            NTupla nt = (NTupla)tbMaterialesOtrasTareas.getModel().getValueAt(tbMaterialesOtrasTareas.getSelectedRow(),0);
            gestorRAM.agregarMaterial(nt.getId());
            this.dispose();;
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelProveedor;
    private javax.swing.JTable tbMaterialesOtrasTareas;
    // End of variables declaration//GEN-END:variables

}
