package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : EstadoOrdenDeCompraRecibidaParcial.java
//  @ Date : 31/08/2010
//  @ Author : 
//
//




public class EstadoOrdenDeCompraRecibidaParcial extends EstadoOrdenDeCompra {

    public EstadoOrdenDeCompraRecibidaParcial() {
        super();
        this.setNombre("Recibida Parcial");
    }

    @Override
    public boolean esAnulada() {
        return false;
    }

    @Override
    public boolean esCancelada() {
        return false;
    }

    @Override
    public boolean esGenerada() {
        return false;
    }

    @Override
    public boolean esPendiente() {
        return false;
    }

    @Override
    public boolean esRecibidaParcial() {
        return true;
    }

    @Override
    public boolean esRecibidaTotal() {
        return false;
    }

    public void setRecibidaTotal(OrdenDeCompra oc){
        oc.setHib_flag_estado("modelo.EstadoOrdenDeCompraRecibidaTotal");
        oc.setEstado(new EstadoOrdenDeCompraRecibidaTotal());
    }

    public void setRecibidaParcial(OrdenDeCompra oc){
        oc.setHib_flag_estado("modelo.EstadoOrdenDeCompraRecibidaParcial");
        oc.setEstado(new EstadoOrdenDeCompraRecibidaParcial());
    }

//	public boolean registrarRecepcion() {
//
//	}
}
