//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : GestorRegistrarNuevaPlanta.java
//  @ Date : 14/06/2010
//  @ Author : 
//
//




public class GestorRegistrarNuevaPlanta {
	public Object listaEmpresas;
	public Object nombrePlanta;
	public Object telefonoPlanta;
	public Object calle;
	public Object altura;
	public Object piso;
	public Object depto;
	public Object listaPais;
	public Object listaProvincia;
	public Object listaLocalidad;
	public Object listaBarrio;
	public Object pais;
	public Object provincia;
	public Object localidad;
	public Object barrio;
	public void mostrarEmpresasCliente() {
	
	}
	
	public void empresaCliente() {
	
	}
	
	public void nombrePlanta() {
	
	}
	
	public void telefonoPlanta() {
	
	}
	
	public void DomicilioPlanta() {
	
	}
	
	public void mostrarPaises() {
	
	}
	
	public void paisPlanta() {
	
	}
	
	public void mostrarProvincias() {
	
	}
	
	public void provinciaPlanta() {
	
	}
	
	public void mostrarLocalidades() {
	
	}
	
	public void LocalidadPlanta() {
	
	}
	
	public void mostrarBarrios() {
	
	}
	
	public void barrioPlanta() {
	
	}
	
	public void PlantaConfirmada() {
	
	}
	
	public void CrearPlanta() {
	
	}
	
	public void noConfirmacionRegistrarContacto() {
	
	}
	
	public void noConfirmacionRegistrarContacto() {
	
	}
}
