//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : GestorRegistrarNuevaEmpresaCliente.java
//  @ Date : 14/06/2010
//  @ Author : 
//
//




public class GestorRegistrarNuevaEmpresaCliente {
	private Object paises;
	private Object provincias;
	private Object localidades;
	private Object barrios;
	private Object pais;
	private Object provincia;
	private Object localidad;
	private Object barrio;
	private Object cuit;
	private Object email;
	private Object telefonos;
	private Object domicilio;
	public void finCU() {
	
	}
	
	public void llamarCURegistrarNuevaPlanta() {
	
	}
	
	public void mostrarNombrePaises() {
	
	}
	
	public void seleccionPais() {
	
	}
	
	public void seleccionProvincia() {
	
	}
	
	public void seleccionLocalidad() {
	
	}
	
	public void seleccionBarrio() {
	
	}
	
	public void nombreEmpresa() {
	
	}
	
	public void CUIT() {
	
	}
	
	public void datosDomicilio() {
	
	}
	
	public void EMail() {
	
	}
	
	public void telefono() {
	
	}
	
	public void seleccionTipoTelefono() {
	
	}
	
	public void agregarNuevaPlanta() {
	
	}
	
	public void confirmacionRegistro() {
	
	}
	
	public void mostrarTiposTelefono() {
	
	}
	
	public void registrarNuevaEmpresa() {
	
	}
	
	public void mostrarLocalidades() {
	
	}
	
	public void mostrarProvincias() {
	
	}
	
	public void mostrarBarrios() {
	
	}
}
