//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : Capacitador.java
//  @ Date : 14/06/2010
//  @ Author : 
//
//




public class Capacitador {
	private ientos.TipoCapacitacion tipoCapacitacion;
	public void crear() {
	
	}
	
	public void mostrarCapacitador() {
	
	}
	
	public void getNombre() {
	
	}
	
	public void mostrarNombreCapacitadores() {
	
	}
	
	public void esCapacitador() {
	
	}
}
