package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : EstadoOrdenDeCompraAnulada.java
//  @ Date : 31/08/2010
//  @ Author : 
//
//




public class EstadoOrdenDeCompraAnulada extends EstadoOrdenDeCompra {

    public EstadoOrdenDeCompraAnulada() {
        super();
        this.setNombre("Anulada");
    }

    //    public void crear() {
//
//    }
//	
//    public boolean anularOrdenDeCompra(OrdenDeCompra oc) {
//        oc.setHib_flag_estado("modelo.EstadoPedidoObraPlaficado");
//        oc.setEstado(new EstadoO);
//    }

    @Override
    public boolean esAnulada() {
        return true;
    }

    @Override
    public boolean esCancelada() {
        return false;
    }

    @Override
    public boolean esGenerada() {
        return false;
    }

    @Override
    public boolean esPendiente() {
        return false;
    }

    @Override
    public boolean esRecibida() {
        return false;
    }
}
