//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : impresora.java
//  @ Date : 14/06/2010
//  @ Author : 
//
//




public class impresora {
	public void imprimir() {
	
	}
}
