package modelo;

//

import java.util.List;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto2010_Requerimientos-iuga
//  @ File Name : Tarea.java
//  @ Date : 08/10/2010
//  @ Author : 
//
//

public class Tarea {
    private int id;
    private GrupoDeTrabajo grupo;
    private String ubicacion;
    private String descripcion;
    private DetalleMaterial detallesMaterial;
    private DetalleConsumible detallesConsumible;
    private List<HerramientaDeEmpresa> herramientas;

    public void CalcularMontoTotal() {

    }

    public Tarea() {
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public DetalleConsumible getDetallesConsumible() {
        return detallesConsumible;
    }

    public void setDetallesConsumible(DetalleConsumible detallesConsumible) {
        this.detallesConsumible = detallesConsumible;
    }

    public DetalleMaterial getDetallesMaterial() {
        return detallesMaterial;
    }

    public void setDetallesMaterial(DetalleMaterial detallesMaterial) {
        this.detallesMaterial = detallesMaterial;
    }

    public GrupoDeTrabajo getGrupo() {
        return grupo;
    }

    public void setGrupo(GrupoDeTrabajo grupo) {
        this.grupo = grupo;
    }

    public List<HerramientaDeEmpresa> getHerramientas() {
        return herramientas;
    }

    public void setHerramientas(List<HerramientaDeEmpresa> herramientas) {
        this.herramientas = herramientas;
    }

    public int getId() {
        return id;
    }

    private void setId(int id) {
        this.id = id;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
}
